{% set version = '4-8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rjags
  version: {{ version|replace("-", "_") }}

source:
  fn: rjags_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rjags_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rjags/rjags_{{ version }}.tar.gz
  sha256: 1529827ab11493fb5f05552e239d700ae2f818995d86d3c9e4c92523f594b59f

  patches:
    - 0001-fix-module-path.diff
    - 0002-WIN32-fix-include-dir.patch
    - 0003-WIN32-fix-libjags-4.dll-dir.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  skip: true  # [win]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/
    - lib/JAGS/modules-4/

# Suggests: tcltk
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}patch             # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-coda >=0.13
    - r-lattice
    - {{native}}jags 4.*
    - {{native}}libopenblas      # [not win]
    - {{native}}openblas         # [win]

  run:
    - r-base
    - r-lattice
    - {{native}}gcc-libs         # [win]
    - r-coda >=0.13
    - {{native}}jags 4.*
    - {{native}}libopenblas      # [not win]
    - {{native}}openblas         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rjags')"           # [not win]
    - "\"%R%\" -e \"library('rjags')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://mcmc-jags.sourceforge.net
  license: GPL (== 2)
  summary: Interface to the JAGS MCMC library.
  license_family: GPL2

extra:
  recipe-maintainers:
    - micknudsen
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: rjags
# Version: 4-8
# Date: 2018-10-19
# Title: Bayesian Graphical Models using MCMC
# Authors@R: c(person("Martyn", "Plummer", role=c("aut","cre"), email="martyn.plummer@gmail.com"), person("Alexey", "Stukalov", role="ctb"), person("Matt", "Denwood", role="ctb"))
# Depends: R (>= 2.14.0), coda (>= 0.13)
# SystemRequirements: JAGS 4.x.y
# URL: http://mcmc-jags.sourceforge.net
# Suggests: tcltk
# Description: Interface to the JAGS MCMC library.
# License: GPL (== 2)
# NeedsCompilation: yes
# Packaged: 2018-10-19 17:03:26 UTC; martyn
# Author: Martyn Plummer [aut, cre], Alexey Stukalov [ctb], Matt Denwood [ctb]
# Maintainer: Martyn Plummer <martyn.plummer@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-10-19 18:00:02 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
